### PR TITLE
Fix path handling for Windows and paths with spaces.

### PR DESCRIPTION
**Pull request by scharris**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Could you please rebase it on master? Thanks!

**Comment by scharris** [comment]
Wasn't quite sure how - can you give a quick pointer?  Would adding a remote ref to the original and then merging from there do it?

**Comment by IvanUkhov** [comment]
```bash
git remote add upstream https://github.com/cmr/openblas-provider.git
git fetch upstream
git rebase upstream/master
```

After the last command, you’ll see a conflict. Open `build.rs` and remove old chunks.

```
git add build.rs
git rebase --continue
git push --force
```

**Comment by IvanUkhov** [comment]
But personally I’d just discard the commit, merge the latest changes from `upstream/master`, reapply the changes, and create a new commit. Then `git push -f` to overwrite what you currently have on GitHub. If you do this, the new commit will be ascribe to your GitHub account (your current commit was created with a different email).

**Comment by scharris** [comment]
Thanks for the help, the rebase and force push are done.

**Comment by IvanUkhov** [comment]
Hmm, that’s interesting. Check out what Travis CI says (the Details link above). Apparently neither GNU/Linux nor Darwin likes those quotes.

**Comment by IvanUkhov** [comment]
I guess I’ll take it from here. I’ll merge your changes and adjust them to make it all work on those two OS’ too. Thank you for your time!

**Comment by scharris** [comment]
Hmm - had been tested on my Ubuntu (15.10) and was working fine.  Not sure what's going on there.  In any case, thanks for taking it over!

**Comment by IvanUkhov** [comment]
I’m removing the quotes, because they don’t help that much (see the following link). As you mentioned yourself, the problem is in OpenBLAS’ scripts, and this is what actually needed to be changed. I’ve already [fixed](https://github.com/xianyi/OpenBLAS/pull/867) what was needed for it to work on Darwin; I hope it will be enough for other platforms too.

**Comment by scharris** [comment]
That's great, a lot more people will benefit with that solution!

**Comment by IvanUkhov** [comment]
So a new version of OpenBLAS, which includes the aforementioned fix, has just been released. I’ve updated `openblas-sys` accordingly.

**Pull request merged**
